permissions:
  contents: read
  packages: write

name: build-docker.yml
on:
  push:
    branches:
      - main
jobs:
  build-frontend:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Node
        uses: actions/setup-node@v3
      - name: Build frontend
        run: |
          cd aurora-front
          npm ci
          npm run build
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: dockerfiles/dockerfile-frontend
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: ghcr.io/day-fit/aurora-frontend:latest
          secrets: |
            gh_name=${{ github.actor }}
            github_token=${{ secrets.GITHUB_TOKEN }}

  build-backend-services:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        service: [core, ai, auth]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./dockerfiles/dockerfile-${{ matrix.service }}
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: ghcr.io/day-fit/aurora-${{ matrix.service }}:latest
          secrets: |
            gh_name=${{ github.actor }}
            github_token=${{ secrets.GITHUB_TOKEN }}